### PR TITLE
[WIP] Try to set up a basic developer shell

### PR DESCRIPTION
**Pull request by yvan-sraka**

### CODE REVIEW

**Comment by yvan-sraka** [comment]
@andreabedini what do you think of this? I currently keep rebasing my PR on this when I need a working HLS …

**Comment by andreabedini** [comment]
I'd prefer to keep `.direnv` out of the repo. We cannot just remove the static binary build, we need to find a way to make it work.

**Comment by andreabedini** [comment]
I tried this myself. The reason you cannot find the ghc is because the cross-compiler is called `x86_64-unknown-linux-musl-ghc`. Ok, maybe we should make a distinction between the devShell and the final binary. Or perhaps just put the static binary as a different output.

**Comment by andreabedini** [comment]
Let me close this and we will rework the static builds in #54 (along with other things).

**Pull request closed without merging**
