### PR TITLE
Support passing --netrc or --netrc-file to curl

### LINKED ISSUE #28: Including a package from a private repository
Is there a way to specify authentication for `foliage build` in order to include a package from a private repository? It looks `foliage build` is using curl so maybe a way to specify a `netrc` file with GitHub credentials by passing `--netrc`, `--netrc-optional` or `--netrc-file` to curl.

```
🌿 Foliage
# buildAction
Current time set to 2022-12-14T16:35:55Z. You can set a fixed time using the --current-time option.
# webpages / index (for buildAction)
# webpages / all-packages (for buildAction)
# webpages / all-package-versions (for buildAction)
# webpages / package / ACME-0.0.0.0 (for buildAction)
# webpages / package / ACME-0.0.0.1 (for buildAction)
# curl (for RemoteAsset https://github.com/topagentnetwork/message-db/tarball/8fd7abc0d2267df014d6ed02125be9ebf86f98fe)
tar xzf _cache/https/github.com/topagentnetwork/message-db/tarball/8fd7abc0d2267df014d6ed02125be9ebf86f98fe -C /tmp/extra-dir-29524655797

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
foliage: Error when running Shake build system:
  at want, called at app/Foliage/CmdBuild.hs:42:7 in main:Foliage.CmdBuild
* Depends on: buildAction
  at apply1, called at app/Foliage/PrepareSource.hs:33:31 in main:Foliage.PrepareSource
* Depends on: PrepareSourceRule (PackageIdentifier {pkgName = PackageName "message-db", pkgVersion = mkVersion [0,1,0,0]}) (PackageVersionSpec {packageVersionTimestamp = Just 2022-12-14 00:08:35 UTC, packageVersionSource = GitHubSource {githubRepo = "topagentnetwork/message-db", githubRev = "8fd7abc0d2267df014d6ed02125be9ebf86f98fe", subdir = Just "message-db"}, packageVersionRevisions = [], packageVersionForce = False})
  at cmd_, called at app/Foliage/PrepareSource.hs:92:17 in main:Foliage.PrepareSource
* Raised the exception:
Development.Shake.cmd, system command failed
Command line: tar xzf _cache/https/github.com/topagentnetwork/message-db/tarball/8fd7abc0d2267df014d6ed02125be9ebf86f98fe -C /tmp/extra-dir-29524655797
Exit code: 2
Stderr:
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

### PR DESCRIPTION
**Pull request by andreabedini**
Closes #28

### CODE REVIEW

**Comment by andreabedini** [comment]
@johnhampton can you check if this works for you?

**Comment by michaelpj** [comment]
If the desire is to pass a bunch of additional options to curl, perhaps we should recommend that people just put a wrapper for curl on the path that adds the options? We could in principle otherwise end up passing through lots of options.

**Comment by andreabedini** [comment]
Wrapping curl might be a bit onerous but why not using `.curlrc`? (Why didn’t I think of it before??).

**Comment by johnhampton** [comment]
> @johnhampton can you check if this works for you?

This worked for me. Thank you!

> Wrapping curl might be a bit onerous but why not using `.curlrc`? (Why didn’t I think of it before??).

I'm not a curl expert so I missed the `.curlrc` option. Allowing that to be specified  with `curl --config` would also work.

**Comment by andreabedini** [comment]
I prefer to document how to use `.curlrc` rather than adding specific support for it in foliage.

**Comment by johnhampton** [comment]
@andreabedini Do you have any interest in putting in an option to specify the curlrc file? It would be way more flexible than having to put one in the home directory.

**Comment by andreabedini** [comment]
@johnhampton I think curl come to help again:

```
              When curl is invoked, it (unless --disable is used) checks for a default config file and uses it if found, even when --config is used. The default con-
              fig file is checked for in the following places in this order:

              1) "$CURL_HOME/.curlrc"

              2) "$XDG_CONFIG_HOME/.curlrc" (Added in 7.73.0)

              3) "$HOME/.curlrc"

              ...           
```

setting `CURL=$PWD` should be enough to have curl look into the current directory.

**Pull request closed without merging**
